// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BuscarPosts(arg1:number,arg2:number):Promise<main.PostsListDTO>;

export function EditarResposta(arg1:string,arg2:string,arg3:string):Promise<void>;

export function EnviarResposta(arg1:string,arg2:string):Promise<main.CommentDTO>;

export function GerarSugestoes(arg1:string):Promise<void>;

export function GetConfig():Promise<main.ConfigDTO>;

export function LastError():Promise<string>;

export function ListarPosts():Promise<main.PostsListDTO>;

export function SaveConfig(arg1:main.ConfigDTO):Promise<void>;
