// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuscarPosts(arg1, arg2) {
  return window['go']['main']['App']['BuscarPosts'](arg1, arg2);
}

export function EditarResposta(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditarResposta'](arg1, arg2, arg3);
}

export function EnviarResposta(arg1, arg2, arg3) {
  return window['go']['main']['App']['EnviarResposta'](arg1, arg2, arg3);
}

export function GerarSugestoes(arg1) {
  return window['go']['main']['App']['GerarSugestoes'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function LastError() {
  return window['go']['main']['App']['LastError']();
}

export function ListarPosts() {
  return window['go']['main']['App']['ListarPosts']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
